name: CI/CD for Ionic App

on:
  push:
    branches:
      - main
      - 1103
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Build Ionic App
        run: ionic build --prod

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          echo "sdk.dir=$HOME/android-sdk" > android/local.properties

      - name: Verify Android SDK Installation
        run: |
          ls -la $HOME/android-sdk/cmdline-tools/latest/bin

      - name: Install Android SDK Packages
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Sync Capacitor with Android
        run: |
          npx cap sync android

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: List APK Files
        run: |
          ls -R android/app/build/outputs/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk